version: 1.0.{build}
skip_tags: true
configuration: Release
platform: Any CPU
environment:
  COVERALLS_REPO_TOKEN:
    secure: 5lcnboADk86wHJTlkrnpCBu/buqGsidnhwKSrwQ2krNFcQTuMqx7wDWTI6dqmXaY
build:
  project: .\src\FluentBuilder.sln
  publish_nuget: true
  verbosity: minimal
deploy:
- provider: NuGet
  api_key:
    secure: 3xvCgvAI98AEDmf9MqhUpBT8LHHuSt6u9/umq7jIzLQowPwnJLUOZH39ohM9sS4b
test_script:
- ps: >-
    .\src\packages\OpenCover.4.6.166\tools\OpenCover.Console.exe -register:user -target:nunit-console.exe -register:user "-targetargs:""src\Nosbor.FluentBuilder.Tests\bin\$env:CONFIGURATION\Nosbor.FluentBuilder.Tests.dll"" /noshadow" -filter:"+[Nosbor.FluentBuilder*]*" -filter:"-[Nosbor.FluentBuilder.Tests]*" -output:opencoverCoverage.xml

    $coveralls = (Resolve-Path "src/packages/coveralls.io.*/tools/coveralls.net.exe").ToString()

    & $coveralls --opencover opencoverCoverage.xml --full-sources