version: 1.0.{build}
skip_tags: true
configuration: Release
platform: Any CPU
environment:
  COVERALLS_REPO_TOKEN:
    secure: JPrgnm1mY5IPLLIPt6aUhRNjSyqUWehZO
build:
  project: .\src\FluentBuilder.sln
  publish_nuget: true
  verbosity: minimal
deploy:
- provider: NuGet
  api_key:
    secure: 3xvCgvAI98AEDmf9MqhUpBT8LHHuSt6u9/umq7jIzLQowPwnJLUOZH39ohM9sS4b
test_script:
- ps: >-
    .\src\packages\OpenCover.4.6.166\tools\OpenCover.Console.exe -register:user -target:nunit-console.exe -register:user "-targetargs:""src\Nosbor.FluentBuilder.Tests\bin\$env:CONFIGURATION\Nosbor.FluentBuilder.Tests.dll"" /noshadow" -filter:"+[Nosbor.FluentBuilder*]*" -output:opencoverCoverage.xml
	
    Resolve-Path "src/packages/coveralls.net.*/tools/csmacnz.coveralls.exe" --opencover -i opencoverCoverage.xml --repoToken $env:COVERALLS_REPO_TOKEN --commitId $env:APPVEYOR_REPO_COMMIT --commitBranch $env:APPVEYOR_REPO_BRANCH --commitAuthor $env:APPVEYOR_REPO_COMMIT_AUTHOR --commitEmail $env:APPVEYOR_REPO_COMMIT_AUTHOR_EMAIL --commitMessage $env:APPVEYOR_REPO_COMMIT_MESSAGE --jobId $env:APPVEYOR_JOB_ID
