version: 1.1.{build}
skip_tags: true
configuration: Release
platform: Any CPU
environment:
  COVERALLS_REPO_TOKEN:
    secure: 5lcnboADk86wHJTlkrnpCBu/buqGsidnhwKSrwQ2krNFcQTuMqx7wDWTI6dqmXaY
before_build:
- appveyor-retry dotnet restore -v Minimal
build_script:
- cmd: dotnet build "src\Nosbor.FluentBuilder" -c %CONFIGURATION% --no-dependencies
- cmd: dotnet build "src\Nosbor.FluentBuilder.Br" -c %CONFIGURATION% --no-dependencies
after_build:
- dotnet pack "src\Nosbor.FluentBuilder" -c %CONFIGURATION% --no-build -o artifacts
- dotnet publish "src\Nosbor.FluentBuilder" -c %CONFIGURATION% --no-build -o artifacts\Nosbor.FluentBuilder
- dotnet pack "src\Nosbor.FluentBuilder.Br" -c %CONFIGURATION% --no-build -o artifacts
- dotnet publish "src\Nosbor.FluentBuilder.Br" -c %CONFIGURATION% --no-build -o artifacts\Nosbor.FluentBuilder.Br
artifacts:
- path: artifacts\**\*.nupkg
deploy:
- provider: NuGet
  api_key:
    secure: 3xvCgvAI98AEDmf9MqhUpBT8LHHuSt6u9/umq7jIzLQowPwnJLUOZH39ohM9sS4b
test_script:
- dotnet test "src\Nosbor.FluentBuilder.Tests" -f netcoreapp1.0
after_test:
- cmd: OpenCover.Console.exe -register:user -filter:"+[*]*" -target:"dotnet.exe" -targetargs:"test src\Nosbor.FluentBuilder.Tests" -output:coverage.xml