version: 1.0.{build}
skip_tags: true
configuration: Release
platform: Any CPU
environment:
  COVERALLS_REPO_TOKEN:
    secure: 5lcnboADk86wHJTlkrnpCBu/buqGsidnhwKSrwQ2krNFcQTuMqx7wDWTI6dqmXaY
before_build:
- appveyor-retry dotnet restore -v Minimal
build_script:
- dotnet build "src\Nosbor.FluentBuilder" -c %CONFIGURATION% --no-dependencies --version-suffix "ci-%APPVEYOR_BUILD_NUMBER%"
- dotnet build "src\Nosbor.FluentBuilder.Br" -c %CONFIGURATION% --no-dependencies --version-suffix "ci-%APPVEYOR_BUILD_NUMBER%"
after_build:
- dotnet pack "src\Nosbor.FluentBuilder" -c %CONFIGURATION% --no-build --version-suffix "ci-%APPVEYOR_BUILD_NUMBER%" -o artifacts
- dotnet pack "src\Nosbor.FluentBuilder.Br" -c %CONFIGURATION% --no-build --version-suffix "ci-%APPVEYOR_BUILD_NUMBER%" -o artifacts
- dotnet publish "src\Nosbor.FluentBuilder" -c %CONFIGURATION% --no-build --version-suffix "ci-%APPVEYOR_BUILD_NUMBER%" -o artifacts\Nosbor.FluentBuilder
- dotnet publish "src\Nosbor.FluentBuilder.Br"  -c %CONFIGURATION% --no-build --version-suffix "ci-%APPVEYOR_BUILD_NUMBER%" -o artifacts\Nosbor.FluentBuilder.Br
artifacts:
- path: artifacts\**\*.*
deploy:
- provider: NuGet
  api_key:
    secure: 3xvCgvAI98AEDmf9MqhUpBT8LHHuSt6u9/umq7jIzLQowPwnJLUOZH39ohM9sS4b
test_script:
- dotnet test "src\Nosbor.FluentBuilder.Tests" -f netcoreapp1.0
